[package]
name = "ffpb"
version = "0.1.2"
edition = "2021"
description = "A coloured progress bar for ffmpeg."
repository = "https://github.com/clitic/ffpb-rs"
documentation = "https://docs.rs/ffpb"
categories = ["command-line-interface"]
license = "MIT"
readme = "README.md"

[dependencies]
regex = "1.10"
kdam = { version = "0.5", features = ["rich"] }
